services:
  frontend:
    build:
      context: ../../services/frontend
    image: udo-frontend:local
    container_name: ${COMPOSE_PROJECT_NAME:-udo}_frontend
    environment:
      - VITE_API_BASE=http://backend:8000
    depends_on:
      - backend
      - openmetadata-server
    ports:
      - "3080:80"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 3s
      retries: 5
    networks:
      - udo-net

networks: {}
