services:
  langchain-api:
    image: python:3.11-slim
    restart: unless-stopped
    working_dir: /app
    command: bash -c "pip install --no-cache-dir fastapi uvicorn langchain openai tiktoken pydantic==2.* && uvicorn main:app --host 0.0.0.0 --port 8090"
    environment:
      PYTHONUNBUFFERED: "1"
    volumes:
      - ../../services/langchain:/app
    ports:
      - "8090:8090"
    networks:
      - udo-net
