services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: s3://mlflow-artifacts
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    volumes:
      - mlflow-data:/mlflow
    command: ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--host", "0.0.0.0", "--port", "5000", "--artifacts-destination", "s3://mlflow-artifacts"]
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/2.0/mlflow/experiments/list" ]
      interval: 45s
      timeout: 10s
      retries: 10
    depends_on:
      - minio
    networks:
      - udo-net

volumes:
  mlflow-data:

