services:
  ogem:
    build:
      context: ../../services/ogem
      dockerfile: Dockerfile
    image: udo-ogem:local
    profiles: ["ogem"]
    restart: unless-stopped
    environment:
      OGEM_PORT: 4500
    ports:
      - "4500:4500"
    networks:
      - udo-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://localhost:4500/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks: {}
