services:
  prefect:
    image: prefecthq/prefect:2.14.17-python3.11
    restart: unless-stopped
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 30s
      timeout: 5s
      retries: 10
    command: ["prefect", "server", "start", "--host", "0.0.0.0", "--port", "4200"]
    environment:
      PREFECT_API_URL: http://prefect:4200/api
    networks:
      - udo-net

