services:
  vault:
    image: hashicorp/vault:1.15.1
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health" ]
      interval: 30s
      timeout: 5s
      retries: 10
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=root
    networks:
      - udo-net

