services:
  weaviate:
    image: semitechnologies/weaviate:1.24.4
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    ports:
      - "8085:8080"
    volumes:
      - weaviate-data:/var/lib/weaviate
    networks:
      - udo-net

volumes:
  weaviate-data:

