name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build images
        run: |
          docker compose build prefect fastapi
      - name: Run Prefect tests
        run: docker run --rm -v ${{ github.workspace }}/services/prefect:/app udo/prefect pytest tests/
      - name: Run FastAPI tests
        run: docker run --rm -v ${{ github.workspace }}/services/fastapi:/app udo/fastapi pytest tests/
      - name: Lint
        run: |
          pip install flake8 black
          flake8
          black --check .
